databases:
  - name: lantechdata-db
    plan: free
    databaseName: lantechdata
    user: lantechdata

services:
  - type: web
    name: lantechdata-server
    runtime: node
    rootDir: server
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 4000
      - key: DATABASE_URL
        fromDatabase:
          name: lantechdata-db
          property: connectionString
      - key: CLIENT_URL
        sync: false
      - key: PUBLIC_SERVER_URL
        sync: false
      - key: MPESA_CONSUMER_KEY
        sync: false
      - key: MPESA_CONSUMER_SECRET
        sync: false
      - key: MPESA_SHORTCODE
        value: "174379"
      - key: MPESA_PASSKEY
        value: "bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919"
      - key: MPESA_BASE_URL
        value: https://sandbox.safaricom.co.ke
      - key: CONTACT_TO_EMAIL
        sync: false
